apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-frontend
  template:
    metadata:
      labels:
        app: chat-frontend
    spec:
      containers:
      - name: chat-frontend
        image: chat-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5002
        env:
        - name: SERVICE_HOST
          value: "chat-bot-service"
        - name: SERVICE_PORT
          value: "5001"
---
apiVersion: v1
kind: Service
metadata:
  name: chat-frontend-service
spec:
  selector:
    app: chat-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002
  type: LoadBalancer
